barbershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('servicios/', include('servicios.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('carro.urls')),
    
]
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.blog, name='blog'),
    path('categoria/<int:categoria_id>/',views.categoria, name="categoria")
]

carro/urls.py
from django.urls import path
from .import views

app_name="carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
    
]

tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name='Tienda'),
    #path('widget/', views.widget, name='widget'),
    
]

tienda/models.py
from django.db import models

class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=250)
    activo=models.BooleanField(default=True)
    imagen=models.ImageField(upload_to='tienda', null=True, blank=True)
    created=models.DateField(auto_now_add=True)
    update=models.DateField(auto_now_add=True)
    

    class Meta:
        verbose_name="categoriaProd"
        verbose_name_plural="categoriasProd"

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    codigo=models.CharField(max_length=250)
    nombre=models.CharField(max_length=250)
    imagen=models.ImageField(upload_to='tienda', null=True, blank=True)
    marca=models.CharField(max_length=250)
    descripcion=models.TextField(blank=True, null=True)
    precio=models.FloatField()
    categorias=models.ForeignKey(CategoriaProd,on_delete=models.CASCADE)
    destacado=models.BooleanField(default=True)
    descuento=models.BooleanField(default=True)
    activo=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    update=models.DateField(auto_now_add=True)

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

    def __str__(self):
        return self.nombre

carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro 
from tienda.models import Producto

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("Tienda")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("Tienda")
    
def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("Tienda")

def limpiar_carro(request, producto_id):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render, HttpResponse
from .models import Producto

def tienda(request):

    productos=Producto.objects.all()

    return render(request, "tienda/tienda.html", {"productos":productos})

#def widget(request):

 #   productos=Productos.objects.all()
    
  #  return render(request, "carro/widget.html", {"productos":productos})

tienda/templates/carro/widget.html
<!-- Shoping Cart Section Begin -->
<section class="shoping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th class="shoping__product">Productos</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if request.session.carro.items %}
                                {% for key, value in request.session.carro.items %}

                                    <tr>
                                        <td class="shoping__cart__item">
                                            <img src="img/cart/cart-1.jpg" alt="">
                                            <h5>{{value.nombre}}</h5>
                                        </td>
                                        <td class="shoping__cart__price">
                                            ${{value.precio}}
                                        </td>
                                        <td class="shoping__cart__quantity">
                                            <div class="quantity">
                                                <div>
                                                    <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                                                    {{value.cantidad}}
                                                    <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="shoping__cart__total">
                                            $0{{importe_totalparcial_carro}}
                                        </td>
                                        <td class="shoping__cart__item__close">
                                            <span href="{% url 'carro:eliminar' value.producto_id %}" class="icon_close"></span>
                                        </td>
                                    </tr>
                                    
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="4">
                                        <div class="alert alert-danger text-center">
                                            Sin productos
                                        </div>
                                    </td>        
                                </tr>        
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__btns">
                    <a href="#" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                    <a href="#" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                        Upadate Cart</a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__continue">
                    <div class="shoping__discount">
                        <h5>Discount Codes</h5>
                        <form action="#">
                            <input type="text" placeholder="Enter your coupon code">
                            <button type="submit" class="site-btn">APPLY COUPON</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__checkout">
                    <h5>Cart Total</h5>
                    <ul>
                        <li>Subtotal <span>$0</span></li>
                        <li>Total <span>$ {{importe_total_carro}}</span></li>
                    </ul>

                    {% if request.session.carro.items%}
                    <a href="#" class="primary-btn">HACER PEDIDO</a>
                    {% endif%}
                    
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shoping Cart Section End --> 